# Generated by Django 6.0.2 on 2026-02-12 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioAnalysis',
            fields=[
                ('analysis_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('transcript', models.TextField()),
                ('risk_score', models.IntegerField(default=0, help_text='0-100 score')),
                ('is_scam', models.BooleanField(default=False)),
                ('warning_message', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='analysis/audio/')),
                ('duration_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audio_analysis',
                'indexes': [models.Index(fields=['session_id', 'created_at'], name='audio_analy_session_35e5a7_idx'), models.Index(fields=['phone_number'], name='audio_analy_phone_n_7a6adc_idx'), models.Index(fields=['is_scam'], name='audio_analy_is_scam_de11f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('analysis_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('ocr_text', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('SAFE', 'Safe'), ('GREEN', 'Low Risk'), ('YELLOW', 'Medium Risk'), ('RED', 'High Risk')], default='SAFE', max_length=20)),
                ('risk_details', models.TextField(blank=True)),
                ('is_safe', models.BooleanField(default=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='analysis/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'image_analysis',
                'indexes': [models.Index(fields=['session_id', 'created_at'], name='image_analy_session_8bc9ab_idx'), models.Index(fields=['risk_level'], name='image_analy_risk_le_3d1256_idx')],
            },
        ),
    ]
