# Generated by Django 6.0.2 on 2026-02-12 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_sessions',
                'indexes': [models.Index(fields=['last_accessed'], name='user_sessio_last_ac_c42661_idx'), models.Index(fields=['is_active'], name='user_sessio_is_acti_1b3cb1_idx')],
            },
        ),
    ]
