# Generated by Django 6.0.2 on 2026-02-12 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('message', models.TextField()),
                ('context', models.CharField(default='general', help_text='Context type: general, scam, etc', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_messages',
                'indexes': [models.Index(fields=['session_id', 'created_at'], name='chat_messag_session_597c4e_idx'), models.Index(fields=['created_at'], name='chat_messag_created_eb4133_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('NONE', 'No action'), ('BLOCK', 'Block number'), ('REPORT', 'Report to authorities')], default='NONE', max_length=20)),
                ('confidence', models.FloatField(default=0.0, help_text='Confidence score 0-1')),
                ('chat_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='action', to='ai_chat.chatmessage')),
            ],
            options={
                'db_table': 'chat_actions',
            },
        ),
    ]
