# Generated by Django 6.0.2 on 2026-02-26 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0002_chatsession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chat_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ai_chat.chatmessage')),
            ],
            options={
                'db_table': 'chat_message_images',
            },
        ),
    ]
