# Generated by Django 6.0.2 on 2026-02-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0004_alter_chatmessage_session_chatfolder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Structured data like search results, tool outputs, etc', null=True),
        ),
    ]
