# Generated by Django 6.0.1 on 2026-03-01 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0005_chatmessage_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone', models.CharField(choices=[('professional', 'Chuyên nghiệp'), ('friendly', 'Thân thiện'), ('casual', 'Thoải mái'), ('formal', 'Trang trọng'), ('humorous', 'Hài hước')], default='friendly', max_length=30)),
                ('language_style', models.CharField(choices=[('simple', 'Đơn giản, dễ hiểu'), ('detailed', 'Chi tiết, chuyên sâu'), ('concise', 'Ngắn gọn, súc tích')], default='simple', max_length=30)),
                ('custom_name', models.CharField(blank=True, default='', help_text='Custom name for the AI assistant', max_length=50)),
                ('custom_instructions', models.TextField(blank=True, default='', help_text='Additional instructions for the AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chatbot_configs',
            },
        ),
        migrations.CreateModel(
            name='SavedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='ai_chat.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_messages',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'message')},
            },
        ),
    ]
