# Generated by Django 6.0.2 on 2026-02-12 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrashReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_info', models.CharField(max_length=255)),
                ('stack_trace', models.TextField()),
                ('timestamp', models.BigIntegerField(help_text='Unix timestamp in milliseconds')),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('ERROR', 'Error'), ('WARNING', 'Warning')], default='ERROR', max_length=20)),
                ('version', models.CharField(blank=True, help_text='App version', max_length=20)),
                ('os_version', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fixed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'crash_reports',
                'indexes': [models.Index(fields=['created_at'], name='crash_repor_created_8a53a2_idx'), models.Index(fields=['severity'], name='crash_repor_severit_410f3a_idx'), models.Index(fields=['fixed'], name='crash_repor_fixed_709d33_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_type', models.CharField(max_length=100)),
                ('error_message', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'error_logs',
                'indexes': [models.Index(fields=['error_type'], name='error_logs_error_t_6c2e56_idx'), models.Index(fields=['created_at'], name='error_logs_created_008b9a_idx')],
            },
        ),
    ]
