# Generated by Django 6.0.2 on 2026-02-12 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('risk_level', models.CharField(choices=[('SAFE', 'Safe'), ('GREEN', 'Low Risk'), ('YELLOW', 'Medium Risk'), ('RED', 'High Risk')], default='SAFE', max_length=10)),
                ('risk_label', models.CharField(blank=True, max_length=500)),
                ('recommendations', models.JSONField(default=list, help_text='List of recommendations')),
                ('reports_count', models.IntegerField(default=0, help_text='Number of user reports')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'phone_numbers',
                'indexes': [models.Index(fields=['phone_number'], name='phone_numbe_phone_n_e47219_idx'), models.Index(fields=['risk_level'], name='phone_numbe_risk_le_416db7_idx')],
            },
        ),
        migrations.CreateModel(
            name='PhoneReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('SPAM', 'Spam Call'), ('SCAM', 'Scam Call'), ('HARASSMENT', 'Harassment'), ('FRAUD', 'Fraud')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='phone_security.phonenumber')),
            ],
            options={
                'db_table': 'phone_reports',
                'indexes': [models.Index(fields=['created_at'], name='phone_repor_created_594b61_idx'), models.Index(fields=['report_type'], name='phone_repor_report__ca607e_idx')],
            },
        ),
    ]
