# Generated by Django 6.0.2 on 2026-02-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='carrier',
            field=models.CharField(blank=True, help_text='e.g. Viettel, Vinaphone', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='country_code',
            field=models.CharField(default='VN', max_length=5),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='is_virtual',
            field=models.BooleanField(default=False, help_text='Is this a virtual/disposable number?'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='line_type',
            field=models.CharField(blank=True, help_text='Mobile, VoIP, Landline', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='trust_score',
            field=models.FloatField(default=0.0, help_text='Computed confidence/trust score (0.0-100.0)'),
        ),
    ]
