# Generated by Django 6.0.1 on 2026-02-23 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('risk_score', models.IntegerField(db_index=True, default=0, help_text='0-100 risk score')),
                ('domain_age_days', models.IntegerField(blank=True, null=True)),
                ('ssl_valid', models.BooleanField(default=False)),
                ('whois_snapshot', models.JSONField(blank=True, default=dict)),
                ('report_count', models.IntegerField(default=0)),
                ('scam_type', models.CharField(choices=[('police_impersonation', 'Giả danh công an'), ('bank_impersonation', 'Giả mạo ngân hàng'), ('recruitment_scam', 'Lừa tuyển dụng'), ('investment_scam', 'Lừa đầu tư'), ('delivery_scam', 'Giả mạo giao hàng'), ('loan_scam', 'Lừa vay tiền'), ('otp_steal', 'Chiêu trò OTP/2FA'), ('phishing', 'Phishing link'), ('romance_scam', 'Lừa tình cảm'), ('other', 'Khác')], default='phishing', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'ordering': ['-risk_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('Vietcombank', 'Vietcombank'), ('Techcombank', 'Techcombank'), ('BIDV', 'BIDV'), ('VietinBank', 'VietinBank'), ('Agribank', 'Agribank'), ('MBBank', 'MBBank'), ('ACB', 'ACB'), ('VPBank', 'VPBank'), ('TPBank', 'TPBank'), ('Sacombank', 'Sacombank'), ('HDBank', 'HDBank'), ('SHB', 'SHB'), ('MSB', 'MSB'), ('VIB', 'VIB'), ('OCB', 'OCB'), ('Momo', 'Ví Momo'), ('ZaloPay', 'ZaloPay'), ('VNPay', 'VNPay'), ('Other', 'Khác')], db_index=True, max_length=50)),
                ('account_number_hash', models.CharField(db_index=True, help_text='SHA-256 hash of account number', max_length=64)),
                ('account_number_masked', models.CharField(blank=True, help_text='Masked display, e.g. ***456789', max_length=20)),
                ('risk_score', models.IntegerField(db_index=True, default=0)),
                ('report_count', models.IntegerField(default=0)),
                ('scam_type', models.CharField(choices=[('police_impersonation', 'Giả danh công an'), ('bank_impersonation', 'Giả mạo ngân hàng'), ('recruitment_scam', 'Lừa tuyển dụng'), ('investment_scam', 'Lừa đầu tư'), ('delivery_scam', 'Giả mạo giao hàng'), ('loan_scam', 'Lừa vay tiền'), ('otp_steal', 'Chiêu trò OTP/2FA'), ('phishing', 'Phishing link'), ('romance_scam', 'Lừa tình cảm'), ('other', 'Khác')], default='other', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['-risk_score', '-created_at'],
                'unique_together': {('bank_name', 'account_number_hash')},
            },
        ),
        migrations.CreateModel(
            name='EntityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_type', models.CharField(choices=[('phone', 'Phone'), ('domain', 'Domain'), ('account', 'Account')], max_length=10)),
                ('from_entity_id', models.IntegerField()),
                ('to_type', models.CharField(choices=[('phone', 'Phone'), ('domain', 'Domain'), ('account', 'Account')], max_length=10)),
                ('to_entity_id', models.IntegerField()),
                ('link_reason', models.CharField(choices=[('shared_text', 'Shared text'), ('shared_report', 'Shared report'), ('shared_url', 'Shared URL'), ('ocr_match', 'OCR match'), ('manual', 'Manual')], max_length=20)),
                ('confidence', models.FloatField(default=0.5, help_text='0.0 to 1.0 confidence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entity Link',
                'verbose_name_plural': 'Entity Links',
                'indexes': [models.Index(fields=['from_type', 'from_entity_id'], name='core_entity_from_ty_cc9b84_idx'), models.Index(fields=['to_type', 'to_entity_id'], name='core_entity_to_type_fc61a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('phone', 'Số điện thoại'), ('domain', 'Website/URL'), ('account', 'Tài khoản ngân hàng'), ('message', 'Tin nhắn'), ('qr', 'QR Code')], max_length=20)),
                ('target_value', models.CharField(help_text='Normalized: phone number, domain, account info', max_length=500)),
                ('scam_type', models.CharField(choices=[('police_impersonation', 'Giả danh công an'), ('bank_impersonation', 'Giả mạo ngân hàng'), ('recruitment_scam', 'Lừa tuyển dụng'), ('investment_scam', 'Lừa đầu tư'), ('delivery_scam', 'Giả mạo giao hàng'), ('loan_scam', 'Lừa vay tiền'), ('otp_steal', 'Chiêu trò OTP/2FA'), ('phishing', 'Phishing link'), ('romance_scam', 'Lừa tình cảm'), ('other', 'Khác')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('critical', 'Khẩn cấp')], default='medium', max_length=10)),
                ('description', models.TextField()),
                ('evidence_file', models.ImageField(blank=True, null=True, upload_to='reports/evidence/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], db_index=True, default='pending', max_length=10)),
                ('moderation_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('phone', 'Số điện thoại'), ('message', 'Tin nhắn'), ('domain', 'Website/URL'), ('account', 'Tài khoản ngân hàng'), ('qr', 'QR / Ảnh')], max_length=20)),
                ('raw_input', models.TextField(help_text='Original user input')),
                ('normalized_input', models.CharField(blank=True, db_index=True, max_length=500)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('risk_score', models.IntegerField(db_index=True, default=0)),
                ('risk_level', models.CharField(choices=[('SAFE', 'An toàn'), ('GREEN', 'Xanh'), ('YELLOW', 'Cảnh báo'), ('RED', 'Nguy hiểm')], default='SAFE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scan Event',
                'verbose_name_plural': 'Scan Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrendDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('region', models.CharField(blank=True, default='VN', max_length=50)),
                ('scam_type', models.CharField(choices=[('police_impersonation', 'Giả danh công an'), ('bank_impersonation', 'Giả mạo ngân hàng'), ('recruitment_scam', 'Lừa tuyển dụng'), ('investment_scam', 'Lừa đầu tư'), ('delivery_scam', 'Giả mạo giao hàng'), ('loan_scam', 'Lừa vay tiền'), ('otp_steal', 'Chiêu trò OTP/2FA'), ('phishing', 'Phishing link'), ('romance_scam', 'Lừa tình cảm'), ('other', 'Khác')], max_length=30)),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trend Daily',
                'verbose_name_plural': 'Trend Daily',
                'ordering': ['-date'],
                'unique_together': {('date', 'region', 'scam_type')},
            },
        ),
        migrations.CreateModel(
            name='UserAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('phone', 'Số điện thoại'), ('domain', 'Website/URL'), ('account', 'Tài khoản ngân hàng'), ('message', 'Tin nhắn'), ('qr', 'QR Code')], max_length=20)),
                ('target_value', models.CharField(max_length=500)),
                ('risk_level', models.CharField(choices=[('SAFE', 'An toàn'), ('GREEN', 'Xanh'), ('YELLOW', 'Cảnh báo'), ('RED', 'Nguy hiểm')], default='YELLOW', max_length=10)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
