# Generated by Django 6.0.1 on 2026-02-24 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_forumcomment_parent_forumpost_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scanevent',
            name='job_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scanevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('failed', 'Lỗi')], db_index=True, default='completed', max_length=20),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('news', 'Tin tức'), ('guide', 'Hướng dẫn'), ('alert', 'Cảnh báo mới'), ('story', 'Chuyện cảnh giác')], default='guide', max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/covers/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
