# Generated by Django 6.0.2 on 2026-02-24 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_scanevent_job_id_scanevent_status_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='scan_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_reports', to='core.scanevent'),
        ),
    ]
