# Generated by Django 6.0.2 on 2026-02-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True, help_text='Markdown supported bio/about section'),
        ),
    ]
