# Generated by Django 6.0.1 on 2026-02-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='messenger_link',
            field=models.URLField(blank=True, help_text='Link to Facebook Messenger, Zalo, etc.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='forumpostreaction',
            name='reaction_type',
            field=models.CharField(choices=[('helpful', 'Hữu ích'), ('share', 'Chia sẻ'), ('dislike', 'Không thích')], max_length=10),
        ),
    ]
