# Generated by Django 6.0.1 on 2026-02-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile_messenger_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='dislikes_count',
            field=models.IntegerField(default=0),
        ),
    ]
