# Generated by Django 6.0.2 on 2026-02-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_learnlesson_learnscenario_forumpost_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_super_admin',
            field=models.BooleanField(default=False),
        ),
    ]
