# Generated by Django 6.0.1 on 2026-02-25 13:34

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userprofile_is_super_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name='forumcomment',
            name='content',
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='content',
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name='learnlesson',
            name='content',
            field=martor.models.MartorField(),
        ),
    ]
