# Generated by Django 6.0.2 on 2026-02-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_article_content_alter_forumcomment_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanevent',
            name='dkim_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scanevent',
            name='dmarc_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scanevent',
            name='sender_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scanevent',
            name='spf_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
