# Generated by Django 6.0.2 on 2026-02-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_scanevent_dkim_status_scanevent_dmarc_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanevent',
            name='detected_urls',
            field=models.JSONField(blank=True, default=list, help_text='List of URLs found in email/message'),
        ),
    ]
