# Generated by Django 6.0.2 on 2026-02-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_scanevent_detected_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='target_type',
            field=models.CharField(choices=[('phone', 'Số điện thoại'), ('domain', 'Website/URL'), ('account', 'Tài khoản ngân hàng'), ('message', 'Tin nhắn'), ('qr', 'QR Code'), ('email', 'Email')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scanevent',
            name='scan_type',
            field=models.CharField(choices=[('phone', 'Số điện thoại'), ('message', 'Tin nhắn'), ('domain', 'Website/URL'), ('account', 'Tài khoản ngân hàng'), ('qr', 'QR / Ảnh'), ('email', 'Email')], max_length=20),
        ),
        migrations.AlterField(
            model_name='useralert',
            name='target_type',
            field=models.CharField(choices=[('phone', 'Số điện thoại'), ('domain', 'Website/URL'), ('account', 'Tài khoản ngân hàng'), ('message', 'Tin nhắn'), ('qr', 'QR Code'), ('email', 'Email')], max_length=20),
        ),
    ]
