# Generated by Django 6.0.2 on 2026-02-26 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_report_target_type_alter_scanevent_scan_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnquiz',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='core.article'),
        ),
        migrations.AddField(
            model_name='learnscenario',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='core.article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='forumcomment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='learnlesson',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='learnquiz',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='core.learnlesson'),
        ),
    ]
