# Generated by Django 6.0.1 on 2026-02-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onesignal_player_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
