# Generated by Django 6.0.2 on 2026-02-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_userprofile_onesignal_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='AI analysis of the report and OCR text'),
        ),
        migrations.AddField(
            model_name='report',
            name='ocr_text',
            field=models.TextField(blank=True, help_text='Text extracted from evidence_file via OCR'),
        ),
    ]
