# Generated by Django 6.0.2 on 2026-02-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_report_ai_analysis_report_ocr_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanevent',
            name='scan_type',
            field=models.CharField(choices=[('phone', 'Số điện thoại'), ('message', 'Tin nhắn'), ('domain', 'Website/URL'), ('account', 'Tài khoản ngân hàng'), ('qr', 'QR / Ảnh'), ('email', 'Email'), ('file', 'Tệp tin')], max_length=20),
        ),
    ]
