# Generated by Django 6.0.1 on 2026-02-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_file_scan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanevent',
            name='scan_type',
            field=models.CharField(choices=[('phone', 'Số điện thoại'), ('message', 'Tin nhắn'), ('domain', 'Website/URL'), ('account', 'Tài khoản ngân hàng'), ('qr', 'QR / Ảnh'), ('email', 'Email'), ('file', 'Tệp tin'), ('audio', 'Âm thanh')], max_length=20),
        ),
    ]
