# Generated by Django 6.0.2 on 2026-02-28 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_learnquiz_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnscenario',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='core.learnlesson'),
        ),
    ]
