# Generated by Django 6.0.2 on 2026-03-03 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_learn_reactions_article_comments'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webpushsubscription',
            new_name='core_webpus_user_id_65cc10_idx',
            old_name='core_webpus_user_id_0eef6c_idx',
        ),
    ]
