# Generated by Django 6.0.2 on 2026-03-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_scamiqattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='scamiqattempt',
            name='ai_feedback',
            field=models.JSONField(blank=True, default=dict, help_text='AI evaluation for simulation questions'),
        ),
        migrations.AddField(
            model_name='scamiqattempt',
            name='is_ai_scored',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
