# Generated by Django 6.0.1 on 2026-03-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_scamiqattempt_ai_feedback_scamiqattempt_is_ai_scored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('news', 'Tin tức'), ('guide', 'Hướng dẫn'), ('alert', 'Cảnh báo mới'), ('story', 'Chuyện cảnh giác'), ('inclusive', 'An ninh số Bao trùm')], default='guide', max_length=20),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='category',
            field=models.CharField(choices=[('warning', 'Cảnh báo'), ('discussion', 'Thảo luận'), ('experience', 'Kinh nghiệm'), ('question', 'Hỏi đáp'), ('inclusive_security', 'An ninh số Bao trùm (GG & LGBTQ+)')], default='discussion', max_length=20),
        ),
        migrations.AlterField(
            model_name='learnlesson',
            name='category',
            field=models.CharField(choices=[('news', 'Tin tức'), ('guide', 'Hướng dẫn'), ('alert', 'Cảnh báo mới'), ('story', 'Chuyện cảnh giác'), ('inclusive', 'An ninh số Bao trùm')], default='guide', max_length=20),
        ),
    ]
