# Generated by Django 6.0.1 on 2026-03-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_article_category_alter_forumpost_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accolade_description',
            field=models.TextField(blank=True, help_text='Mô tả vinh danh đặc biệt'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='accolade_title',
            field=models.CharField(blank=True, help_text='Danh hiệu vinh danh', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('non_binary', 'Phi nhị nguyên giới (Non-binary)'), ('genderqueer', 'Genderqueer'), ('agender', 'Vô giới (Agender)'), ('transgender', 'Người chuyển giới (Transgender)'), ('intersex', 'Liên giới tính (Intersex)'), ('two_spirit', 'Two-spirit'), ('other', 'Khác'), ('prefer_not_to_say', 'Không muốn tiết lộ')], default='prefer_not_to_say', max_length=30),
        ),
    ]
