# Generated by Django 6.0.1 on 2026-03-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_userprofile_accolade_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('non_binary', 'Phi nhị nguyên giới (Non-binary)'), ('transgender', 'Người chuyển giới (Transgender)'), ('gender_fluid', 'Linh hoạt giới (Genderfluid)'), ('bigender', 'Song giới (Bigender)'), ('genderqueer', 'Giới phi chuẩn (Genderqueer)'), ('agender', 'Vô giới (Agender)'), ('intersex', 'Liên giới tính (Intersex)'), ('other', 'Khác'), ('prefer_not_to_say', 'Tôi không muốn tiết lộ')], default='prefer_not_to_say', max_length=30),
        ),
    ]
