# Generated by Django 6.0.1 on 2026-03-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('news', 'Tin tức'), ('guide', 'Hướng dẫn'), ('alert', 'Cảnh báo mới'), ('story', 'Chuyện cảnh giác'), ('inclusive', 'An ninh số Bao trùm'), ('empathy', 'Góc thấu cảm')], default='guide', max_length=20),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='category',
            field=models.CharField(choices=[('warning', 'Cảnh báo'), ('discussion', 'Thảo luận'), ('experience', 'Kinh nghiệm'), ('question', 'Hỏi đáp'), ('lgbtq_safety', 'An toàn LGBTQ+'), ('women_security', 'Phụ nữ & An ninh số'), ('healing_stories', 'Chữa lành & Chia sẻ')], default='discussion', max_length=20),
        ),
        migrations.AlterField(
            model_name='learnlesson',
            name='category',
            field=models.CharField(choices=[('news', 'Tin tức'), ('guide', 'Hướng dẫn'), ('alert', 'Cảnh báo mới'), ('story', 'Chuyện cảnh giác'), ('inclusive', 'An ninh số Bao trùm'), ('empathy', 'Góc thấu cảm')], default='guide', max_length=20),
        ),
    ]
