# Generated by Django 5.2.17 on 2026-09-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_article_category_alter_forumpost_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='category',
            field=models.CharField(choices=[('warning', 'Cảnh báo'), ('discussion', 'Thảo luận'), ('experience', 'Kinh nghiệm'), ('question', 'Hỏi đáp')], default='discussion', max_length=20),
        ),
    ]
