# Generated by Django 5.2.17 on 2026-09-15 06:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_forumpost_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên định danh khóa (ví dụ: Claude Desktop, Cursor, Dev Bot)', max_length=120)),
                ('prefix', models.CharField(db_index=True, help_text='Tiền tố hiển thị (ví dụ: sc_live_abcd1234)', max_length=24)),
                ('hashed_key', models.CharField(db_index=True, help_text='SHA-256 hash của API key bí mật', max_length=128, unique=True)),
                ('tier', models.CharField(choices=[('free', 'Cơ bản (Free - 500 req/ngày)'), ('developer', 'Lập trình viên (Developer - 2.000 req/ngày)'), ('unlimited', 'Không giới hạn (Unlimited/Admin)')], default='free', max_length=20)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60)),
                ('daily_quota', models.PositiveIntegerField(default=500)),
                ('monthly_quota', models.PositiveIntegerField(default=15000)),
                ('requests_today', models.PositiveIntegerField(default=0)),
                ('requests_this_month', models.PositiveIntegerField(default=0)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('last_reset_date', models.DateField(default=django.utils.timezone.now)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
